#!/usr/bin/env node
var exec = require("child_process").exec;
console.log(__filename)
exec('catdoc ' + __filename,
  function (error, stdout, stderr) {
    if (error) {
      console.log("catdoc cannot be found/executed by this script, errors to follow.")
      console.log("**************ERROR*****************");
      console.log(error);
      console.log("**************stderr*****************")
      console.log(stderr);
      console.log("**************stdout*****************")
      console.log(stdout);
    } else {
      console.log("Found catdoc, textract should be able to use it.")
    }
  }
);