#!/usr/bin/env node
var exec = require("child_process").exec;
exec( "pdftotext -v",
  function( error, stdout, stderr ) {
    if (stderr && stderr.indexOf("pdftotext version") > -1) {
      console.log("Found pdftotext, textract should be able to use it.")
    } else {
      console.log("pdftotext cannot be found/executed by this script, errors to follow.")
      console.log("**************ERROR*****************");
      console.log(error);
      console.log("**************stderr*****************")
      console.log(stderr);
      console.log("**************stdout*****************")
      console.log(stdout);
    }
  }
);